id = "lmd"
name = "lmd"
description = "lmd"
version = "0.0.1"
schema_version = 1
authors = ["Sarah Hawkless <abc@xyz.com>"]
repository = "https://github.com/orlaya/lmd_zed"

[grammars.lmd]
repository = "https://github.com/orlaya/lmd_tree"
commit = "c0255403bb2e10b016e0cc264a1e54cdf2d7c528"
