id = "lmd"
name = "lmd"
description = "lmd"
version = "0.0.1"
schema_version = 1
authors = ["Sarah Hawkless <abc@xyz.com>"]
repository = "https://github.com/orlaya/lmd_zed"

[grammars.lmd]
repository = "https://github.com/orlaya/lmd_tree"
commit = "f41d82c982d5be93b897f2c1d97b76de2a0e8fc5"
