id = "lmd"
name = "lmd"
description = "lmd"
version = "0.0.1"
schema_version = 1
authors = ["Sarah Hawkless <abc@xyz.com>"]
repository = "https://github.com/orlaya/lmd_zed"

[grammars.lmd]
repository = "https://github.com/orlaya/lmd_tree"
commit = "604a86930b2f73e81a93d524946e23b3b5e5f8b6"
